spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    com.qfy.demoboot.dao: DEBUG
mybatis:
  # 指向实体类包路径
  type-aliases-package: com.qfy.demoboot.entity
  # mapper xml 文件地址
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  check-config-location: true
  # 执行模式。默认是 SIMPLE
  executor-type: simple